---
logger:
  logLevel: debug
  outputType: text

database:
  user: postgres
  password: postgres
  host: db
  port: 5432
  sslmode: disable

keycloak:
  basePath: http://keycloak:8080
  realm: tempo-time-tracker
